name: "Auto Destruição: 20 de abr de 2025"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 20 4 *'  # Executa em 20 de abril de 2025 às 12:00 UTC

jobs:
  delete-folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Apagar a pasta
        run: |
          rm -rf lgpd  # Substitua pelo nome da pasta a ser removida
          rm -rf .github
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Removendo a pasta automaticamente em 20/02/2025"
          git pull --rebase origin main  # Puxa mudanças antes de enviar
          git push origin main
