name: Delete Folder on Feb 20, 2025

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 20 2 *'  # Executa em 20 de fevereiro de 2025 às 12:00 UTC

jobs:
  delete-folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permite que o bot faça push

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Apagar a pasta
        run: |
          rm -rf redirect  # Substitua pelo nome da pasta a ser removida
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Removendo a pasta automaticamente em 20/02/2025"
          git pull --rebase origin main  # Puxa mudanças antes de enviar
          git push origin main
