name: Delete Folder on Feb 20, 2025

on:
  schedule:
    - cron: '42 19 7 2 *'  # Executa em 20 de fevereiro de 2025 às 12:00 UTC

jobs:
  delete-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Apagar a pasta
        run: |
          rm -rf teste  # Substitua pelo nome da pasta a ser removida
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Removendo a pasta automaticamente em 20/02/2025"
          git push origin main  # Ajuste o branch se necessário
